export const INITIALIZE_CHARACTER = 'INITIALIZE_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const HALVE_CHARACTERS = 'HALVE_CHARACTERS';
export const SELECT_VOTE_PAGE_CHARACTERS = 'SELECT_VOTE_PAGE_CHARACTERS';
export const RATE_CHARACTER = 'RATE_CHARACTER';
export const MATCH_CHARACTERS_AND_ROWS = 'MATCH_CHARACTERS_AND_ROWS';
export const SUBMIT_CHARACTER_RATINGS = 'SUBMIT_CHARACTER_RATINGS';